services:
    wordpress:
        image: wordpress
        restart: always
        ports:
            - 5555:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
            - ./wordpress:/var/www/html
            - ./config/php.ini:/usr/local/etc/php/php.ini

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - ./datas:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./wordpress/wp-content/themes/portfolio-eduardevs:/app
        working_dir: /app
        # Only run composer install when you call it manually
        command: ["bash"]
        stdin_open: true
        tty: true
